import { useMemo } from 'react';
import type { ReadinessSloProfile, RecoveryReadinessPlan } from '@domain/recovery-readiness';
import type { RecoverySignal, RunPlanSnapshot, RunSession } from '@domain/recovery-operations-models';
import { withBrand } from '@shared/core';
import type { ForgeScenario } from '@domain/recovery-command-forge';
import { useRecoveryCommandForgeOrchestrator } from '../hooks/useRecoveryCommandForgeOrchestrator';
import { CommandForgeSimulationBoard } from '../components/recovery-command-forge/CommandForgeSimulationBoard';
import { CommandForgeTopologyTimeline } from '../components/recovery-command-forge/CommandForgeTopologyTimeline';
import { buildExecutionReport, buildPolicy } from '@domain/recovery-command-forge';

interface PageProps {
  readonly tenant: string;
}

const baseReadinessPlan = (tenant: string): RecoveryReadinessPlan => ({
  planId: withBrand(`readiness-${tenant}`, 'RecoveryReadinessPlanId'),
  runId: withBrand(`run-${tenant}`, 'ReadinessRunId'),
  title: `Readiness ${tenant}`,
  objective: 'availability',
  state: 'active',
  createdAt: new Date().toISOString(),
  targets: [],
  windows: [],
  signals: [],
  riskBand: 'green',
  metadata: {
    owner: 'recovery-console',
    tags: ['recovery-command-forge'],
    tenant,
  },
});

const baseSession = (tenant: string): RunSession => ({
  id: withBrand(`session-${tenant}`, 'RunSessionId'),
  runId: withBrand(`run-${tenant}`, 'RecoveryRunId'),
  ticketId: withBrand(`ticket-${tenant}`, 'RunTicketId'),
  planId: withBrand(`plan-${tenant}`, 'RunPlanId'),
  status: 'queued',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  constraints: {
    maxParallelism: 4,
    maxRetries: 2,
    timeoutMinutes: 120,
    operatorApprovalRequired: true,
  },
  signals: [],
});

const baseSnapshot = (tenant: string): RunPlanSnapshot => ({
  id: withBrand(`snapshot-${tenant}`, 'RunPlanId'),
  name: `snapshot-${tenant}`,
  program: {
    id: withBrand(`program-${tenant}`, 'RecoveryProgramId'),
    tenant: withBrand(tenant, 'TenantId'),
    service: withBrand('service', 'ServiceId'),
    name: 'Recovery command program',
    description: 'Generated by stress workspace',
    priority: 'critical',
    mode: 'guided',
    window: {
      start: new Date().toISOString(),
      end: new Date(Date.now() + 3600000).toISOString(),
    },
    topology: {
      rootServices: ['recovery'],
      fallbackServices: ['manual'],
      immutableDependencies: [],
    },
    constraints: [],
    steps: [],
    owner: tenant,
    tags: ['recovery-command-forge'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as unknown as RunPlanSnapshot['program'],
  constraints: {
    maxParallelism: 4,
    maxRetries: 2,
    timeoutMinutes: 120,
    operatorApprovalRequired: true,
  },
  fingerprint: {
    tenant: withBrand(tenant, 'TenantId'),
    region: 'global',
    serviceFamily: 'platform',
    impactClass: 'application',
    estimatedRecoveryMinutes: 15,
  },
  effectiveAt: new Date().toISOString(),
});

const baseSignals = (tenant: string): readonly RecoverySignal[] =>
  Array.from({ length: 16 }).map((_, index) => ({
    id: `${tenant}-signal-${index}`,
    source: index % 2 === 0 ? 'telemetry' : 'runbook',
    severity: (index % 10) + 1,
    confidence: Number((0.2 + index * 0.04).toFixed(2)),
    detectedAt: new Date(Date.now() - index * 30000).toISOString(),
    details: {
      index,
      reason: 'stress',
    },
  }));

const slaProfile: ReadinessSloProfile = {
  profileId: withBrand('slo-profile', 'ReadinessSloProfileId'),
  name: 'Recovery command profile',
  targets: [
    { key: 'mttr', warningAt: 20, criticalAt: 45, unit: 'minutes' },
    { key: 'rto', warningAt: 30, criticalAt: 60, unit: 'minutes' },
  ],
  windowMinutes: 90,
};

const scenarioFromSeed = (tenant: string): ForgeScenario => ({
  tenant,
  readinessPlan: baseReadinessPlan(tenant),
  session: baseSession(tenant),
  planSnapshot: baseSnapshot(tenant),
  signals: baseSignals(tenant),
  budget: {
    parallelismLimit: 5,
    retryLimit: 2,
    maxDurationMinutes: 120,
    approvalRequired: true,
  },
  slaProfile,
});

export const RecoveryCommandForgeWorkspacePage = ({ tenant }: PageProps) => {
  const scenario = useMemo(() => scenarioFromSeed(tenant), [tenant]);
  const simulation = useMemo(() => buildExecutionReport(tenant, scenario, { policyGateEnabled: true }), [tenant, scenario]);
  const reports = useMemo(
    () => [
      simulation,
      ...[15, 30, 60].map((budget) => buildExecutionReport(tenant, scenario, { maxBudgetMinutes: budget, policyGateEnabled: true })),
    ],
    [tenant, scenario, simulation],
  );
  const policy = useMemo(() => buildPolicy({
    urgency: simulation.policy.urgency,
    budget: scenario.budget,
    graphHealth: {
      hasCycles: false,
      averageFanIn: 0.25,
      averageFanOut: 0.25,
      nodeCount: simulation.topologies.length,
      edgeCount: simulation.topologies.reduce((acc, topology) => acc + topology.nodes.length, 0),
    },
    slaWindow: scenario.slaProfile.windowMinutes,
    nodeCount: simulation.topologies.reduce((acc, topology) => acc + topology.nodes.length, 0),
    coverage: 0.75,
    signals: scenario.signals,
    readinessRisk: 'amber',
    priorities: simulation.topologies.reduce<Record<string, number>>((acc, topology) => {
      for (const nodeState of topology.nodes) {
        acc[nodeState.node.id] = nodeState.progress;
      }
      return acc;
    }, {}),
  }), [simulation, scenario]);

  const { state, actions } = useRecoveryCommandForgeOrchestrator(tenant, [scenario]);
  const topologies = simulation.topologies;

  return (
    <main className="recovery-command-forge-workspace">
      <h1>Recovery Command Forge workspace</h1>
      <p>{`tenant=${tenant}`}</p>
      <p>{`policy=${policy.summary}`}</p>
      <div className="controls">
        <button type="button" onClick={() => void actions.run()} disabled={state.running}>Run orchestration</button>
        <button type="button" onClick={() => actions.filter({ minPolicyScore: 50 })} disabled={state.running}>Filter strong</button>
        <button type="button" onClick={() => actions.reset()} disabled={state.running}>Reset</button>
      </div>
      {state.lastError ? <p className="error">{state.lastError}</p> : null}
      <p>{`runs=${state.workspace?.summary.totalRuns ?? 0}`}</p>
      <p>{`selected=${state.selectedRunId ?? 'none'}`}</p>
      {state.workspace ? <pre>{JSON.stringify(state.workspace, null, 2)}</pre> : null}
      <CommandForgeTopologyTimeline topologies={topologies} />
      <CommandForgeSimulationBoard
        reports={reports}
        onSelect={(planId) => {
          actions.pickRun(planId);
        }}
      />
    </main>
  );
};
